### ISSUE TITLE
SSL Configuration Error: doesn't recognize spark-keystore.jks & spark-truststore.jks

### ISSUE THREAD

**Issue by porscheme** [bitnami/bitnami-docker-spark#80] opened 2022-04-20 05:41 UTC
### Name and Version

bitnami/spark:3

### What steps will reproduce the bug?

1. Create spark-truststore.jks using below steps
```
# Enter store password when prompted
keytool -keystore spark-truststore.jks -alias root -importcert -file rootCA.cert.pem -trustcacerts
keytool -keystore spark-truststore.jks -alias intermediate -importcert -file issuingCA.cert.pem -trustcacerts
```

2. Create spark-keystore.jks using below steps
```
# Make PKCS12 cert from crt and key pem files
openssl pkcs12 -export -in ssl.cert.pem -inkey ssl.key.pem -name spark -out spark-pkcs-12.p12
keytool -importkeystore -srckeystore spark-pkcs-12.p12 -srcstoretype PKCS12 -destkeystore spark-keystore.jks -deststoretype jks
```

3. Create K8S secret key
```
kubectl create secret generic sparksecret --from-literal=keystore_password=REDACTED --from-file=spark-keystore.jks=spark-keystore.jks --from-literal=truststore_password=REDACTED --from-file=spark-truststore.jks=spark-truststore.jks -n cohort-workbench
```

4. Deploy Sparck using helm charts

### What is the expected behavior?

SSL security enabled

### What do you see instead?

1. Below is the screen capture on master (initcontainer passed)
[Screenshot 2022-04-14 162133 PNG](https://user-images.githubusercontent.com/29828396/164157781-6492082a-105d-4081-8de8-774cde6d3a74.jpg)

2. Below is the screen capture on worker (stuck in initcontainer)
![Screenshot 2022-04-14 162133 PNG](https://user-images.githubusercontent.com/29828396/164158221-1da1d91f-8990-4a21-ae07-62628c40a0ab.jpg)

**Comment by porscheme** [comment] 2022-04-20 17:32
I made a custom image with both spark-keystore.jks & spark-truststore.jks files copied to the location /opt/bitnami/spark/conf/certs. Spark cluster started fine. Therefore, no issue with the JKS files. 

Mybe this is [Helm charts](https://github.com/bitnami/charts/tree/master/bitnami/spark) issue?

**Comment by dgomezleon** [comment] 2022-04-21 10:00
Hi @porscheme ,

Thanks for reporting it.

Since the issue is related to the chart, could you please open a new issue in [Helm charts](https://github.com/bitnami/charts/tree/master/bitnami/spark) to check it there?

We proceed to close this issue.

**Closed by dgomezleon** 2022-04-21 10:00 UTC
